"""Derive grbl-Mega-5X `$` settings from machine.toml. Unknown values become commented TODO lines."""

from .atc import fmt
from .config import TODO

# $110-$133 rows: (setting, config key under [grbl], description)
_RUNTIME = [
    ("$110", "x_max_rate", "X max rate mm/min"),
    ("$111", "y_max_rate", "Y max rate deg/min"),
    ("$112", "z_max_rate", "Z (magazine) max rate deg/min"),
    ("$113", "a_max_rate", "A (slide) max rate mm/min"),
    ("$120", "x_accel", "X accel mm/s^2"),
    ("$121", "y_accel", "Y accel deg/s^2"),
    ("$122", "z_accel", "Z accel deg/s^2"),
    ("$123", "a_accel", "A accel mm/s^2"),
    ("$130", "x_max_travel", "X max travel mm (= machine.x_max_mm)"),
    ("$131", "y_max_travel", "Y max travel deg (>= 360)"),
    ("$132", "z_max_travel", "Z max travel deg (must cover slot0 + 360)"),
    ("$133", "a_max_travel", "A max travel mm"),
]


def _row(setting, value, note):
    if value in (None, TODO):
        return f"; {setting}=TODO  ({note})"
    return f"{setting}={fmt(value)}  ; {note}"


def settings(cfg):
    m = cfg.get("machine", {})
    spr = float(m.get("motor_steps", 200)) * float(m.get("microsteps", 32))

    def per(key, divisor_key, ratio=1.0, deg=False):
        d = m.get(divisor_key)
        if d in (None, TODO):
            return TODO
        return spr * ratio / (360.0 if deg else float(d))

    lines = [
        "; grbl-Mega-5X settings generated by eggbot-atc. Paste into the UGS console.",
        _row("$100", per("x", "x_lead_mm"), "X steps/mm = motor_steps*microsteps/x_lead_mm"),
        _row("$101", spr * float(m.get("y_gear_ratio", 1)) / 360.0, "Y steps/deg (1 unit = 1 deg of egg)"),
        _row("$102", spr * float(m.get("z_gear_ratio", 1)) / 360.0, "Z steps/deg (magazine)"),
        _row("$103", per("a", "a_lead_mm"), "A steps/mm = motor_steps*microsteps/a_lead_mm"),
    ]
    g = cfg.get("grbl", {})
    overrides = {"x_max_travel": m.get("x_max_mm")}
    for setting, key, note in _RUNTIME:
        lines.append(_row(setting, g.get(key, overrides.get(key)), note))
    lines += [
        "$30=255  ; max S value (pen_up_cmd / pen_down_cmd use this range)",
        "$31=0  ; min S value",
        "$32=0  ; laser mode off",
    ]
    return lines
